### ISSUE TITLE
BRASS depl: prism model allows transitions even without sufficient battery

### ISSUE THREAD

**Issue by bisc** [cmu-able/rainbow#11]
The generated prism model does not have a transition guard that would check whether the robot has enough battery to complete the transition. Instead, it picks max(0, battery - expended_energy) as a new value for the battery. 

Impact: the model permits plans that runs out of battery during the last transition. Following such a plan would result in running out of power. Moreover, it makes the case of battery = 0 ambiguous and (therefore difficult to analyze) because it is not clear whether the robot ran out of power on that transition or it just barely had enough to complete it.

Possible fixes: 
- Adding a guard. This would result in not selecting flawed plans, but also not allow actuation to do its best effort to reach the goal when running out of battery. 
- Adding b>0 as an eventual condition in all PCTL properties where finishing the path is required. It is a workaround, but it probably has the same effects as above.
- Implementing one of the above + augmenting the lower-level actuation response to attempt to complete their motion even when the planner returns no valid plan (only applies when running out of battery). 

There may be more discussion needed on the best-effort actions in actuation when the planner returns no valid plans.

**Comment by schmerl** [comment]
I believe this has been fixed? @bisc

**Comment by bisc** [comment]
Yes, I believe so too.
