### ISSUE TITLE
Implement BRASS Phase 2 Robot State model

### ISSUE THREAD

**Issue by schmerl** [cmu-able/rainbow#13]
Implement the Robot State model that contains the following info:

- Battery charge
- State of each sensor (of Lidar and Kinect)
- Speed
- Head lamp
- Bump state

Do we want location here as well?

**Comment by schmerl** [comment]
I'll take point on implementing this.

To do this, I plan to refactor the MissionState from Phase 1 into this separate Robot model. Subissues of this will be to integrate with the appropriate gauges and probes for getting the information needed.

**Comment by schmerl** [comment]
Created branch feature/robot-state

**Comment by bisc** [comment]
Let's walk through the (either your candidate or old) class design sometime. I recall @ssukkerd had complaints.

**Comment by schmerl** [comment]
I think the complaint was that MissionState conflated information about the robot and the mission. The features above I took from the document on BRASS models.

**Comment by schmerl** [comment]
Resolved along the way.
