### ISSUE TITLE
[MSIT] Deficient documentation about what can be put in the template

### ISSUE THREAD

**Issue by schmerl** [cmu-able/rainbow#60]
The documentation on the initializer specifies the syntax for the template file, but it does not explain what variables can be manipulated. For example, if I put in config.yml an invalid variable, e.g.:

```
model_file_xextension: acme
```
The tool throws an error.

Are all the possible variables that can be set in `config.yml`?

**Comment by jumoni** [comment]
Yes, all possible variables can be set in config.yml as long as your have declared them in templates/metadata.yml. The error you got is caused by putting a variable in config.yml without first declaring it in templates/metadata.yml. We will update the user guide to provide further instructions.
